version: '3'
services:
  mysql:
    container_name: ps-mysql
    restart: unless-stopped
    build:
      context: ./mysql/
      args:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./dbdata
        target: /var/lib/mysql

  phpmyadmin:

    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ps-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 81:80
    networks:
      - prestashop_network

  prestashop:    
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      DB_SERVER: ps-mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_DOMAIN: localhost
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./psdata
        target: /var/www/html

networks:
  prestashop_network:
volumes:
  psdata:
  dbdata:
