version: '3'
services:
  mysql:
    container_name: ps-8.1.2-mysql
    restart: unless-stopped
    build:
      context: ./mysql/
      args:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3318"
    
    networks:
      - prestashop_network-8.1.2
    volumes:
      - type: bind
        source: ./dbdata-8.1.2
        target: /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ps-8.1.2-phpmyadmin
    environment:
      PMA_HOST: ps-8.1.2-mysql
      PMA_PORT: 3318
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 81:80
    networks:
      - prestashop_network-8.1.2

  prestashop:    
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: prestashop8.1.2
    image: prestashop/prestashop:8.1.2
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8018:8018
    environment:
      DB_SERVER: ps-8.1.2-mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      PS_DOMAIN: localhost
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: kontrollpanel
      PS_FOLDER_INSTALL: install4577
    networks:
      - prestashop_network-8.1.2

    volumes:
      - type: bind
        source: ./psdata-8.1.2
        target: /var/www/html/

networks:
  prestashop_network-8.1.2:
volumes:
  psdata-8.1.2:
  dbdata-8.1.2:
